JS Capstone
XRichardroidX/JS-Capstone pull request #54
Opened 2023-01-05 20:58 UTC by michaelamponsah

### **This branch contains an implementation of all requirements;**

- [ x] TV shows from the tv maze API are displayed in cards on the homepage 
- [x] Added logic to display and update comments and like on each tv-show
- [x] Implemented a modal to display detailed tv-show information. 

![capstone-1](https://user-images.githubusercontent.com/42746317/210878473-b3dd85ea-d0e3-46db-9fe1-e21b4142301b.PNG)
![capstone-2](https://user-images.githubusercontent.com/42746317/210878499-73c6c8c8-2e1e-422e-990d-43b2c1eb1447.PNG)
![capstone-3](https://user-images.githubusercontent.com/42746317/210878508-7d3ce2be-2211-46a6-94ad-3b73908f5c69.PNG)

2023-01-05 22:45 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi team,
 ### You have been doing a tremendous job so far :ok_hand:

## To Highlight 🎉
PR has a title and description. :heavy_check_mark:
Git flow is followed. :heavy_check_mark:
No linter errors. :heavy_check_mark:
## To Improve 🙏

- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.
**_Note: Please do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-01-05 22:45 UTC, SajjadAhmad14 commented on src/module/displayComments.js
> +const displayComments = async (index) => {
When the Comments popup loads, the web app is expected to retrieve data from the selected API and show details about the selected item. And likewise, retrieve data from the Involvement API to show the item comments.
When a user clicks on the "Comment" button, the data is expected to get recorded in the `Involvement API` and the screen updated.
Please see the mockup for comments box [here](https://github.com/microverseinc/curriculum-javascript/blob/main/group-capstone/images/Comments.png).

Requirement:

![comments_pop](https://user-images.githubusercontent.com/35504149/210894395-6baa8167-43c6-48dd-a562-90bdeb5d1fca.png)

2023-01-05 22:45 UTC, SajjadAhmad14 commented on src/module/displayComments.js
> +  commentsWrapper.innerHTML = '';
Please add `Counters` in  comments popup to show the number of comments. Kindly see the [mockup](https://github.com/microverseinc/curriculum-javascript/blob/main/group-capstone/images/Comments.png) for comments popup.

Requirement:
![counters](https://user-images.githubusercontent.com/35504149/210894270-9c8f65b6-a079-4f29-b2f4-53151f7effa4.png)

2023-01-05 22:45 UTC, SajjadAhmad14 commented on src/index.html
> +      <nav class="navbar">
Please add `Counters` on home page to show the number of items. Kindly see the [mockup](https://github.com/microverseinc/curriculum-javascript/blob/main/group-capstone/js_capstone.md) for home page. Counter for movies is added in the body of the home page. But it is required to add the counter in the header of the page as it is shown in the given mockup.
Requirements:

![counters](https://user-images.githubusercontent.com/35504149/210892920-131c7d91-87f5-4df6-bb64-bd1f825e9f89.png)

2023-01-05 22:45 UTC, SajjadAhmad14 commented on src/module/displayMoviesData.js
> +    numberOfMovies.innerHTML = `${data.length} Tv Shows`;
Good job for adding counter for movies here, but the requirement is to still create a specific function to calculate counter numbers on each page even if the API provides that information.

2023-01-06 04:18 UTC, michaelamponsah commented on src/index.html
> +      <nav class="navbar">
@SajjadAhmad14, 

Thanks for your review 🚀 !
The details of comments in the popup and the number of items on the homepage works as expected.

2023-01-06 04:21 UTC, michaelamponsah commented on src/module/displayComments.js
> +  commentsWrapper.innerHTML = '';
@SajjadAhmad14, 

The number of comments and likes for each tv-show has been implemented. We would really appreciate your time so we demonstrate our project to you.

2023-01-06 04:23 UTC, michaelamponsah commented on src/module/displayComments.js
> +const displayComments = async (index) => {
@SajjadAhmad14,

The functionality of displaying comments from the involvement API and updating the UI accordingly works as expected.
Do you have a moment for a quick call?

2023-01-06 07:41 UTC, Tadesse-Alemayehu requested changes
### Hi Team

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![199733072-bdacca19-8df9-43a7-be93-3aff2f1c15c8](https://user-images.githubusercontent.com/69077061/204107907-c2532abb-b23d-4fda-88f0-1ec9c7b71971.gif)

 ## Highlights
 - [ ] Good job making most of the changes requested by the previous reviewer. 🙏
 - [ ] Good job overall following the template design 💯
 - [ ]  Correct GitFlow 👍🏾
 - [ ]  Good commit history 🥇
 - [ ]  Good PR title/description 💯
 - [ ]  All linters passed 🥇

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-06 07:41 UTC, Tadesse-Alemayehu commented on src/module/getSingleShowLike.js
> +};
- [Optional] Good job making a separate component for your like counter, Yet we need to have a test case for the like counter, This is among the primary requirements I'm only making it optional because it has not been mentioned to you before.

2023-01-06 07:41 UTC, Tadesse-Alemayehu commented on src/module/displayComments.js
> +};
- [ ] Hello team, I see The number of comments and likes for each tv-show has been implemented. But one thing left is as the previous code reviewer mentioned. we need to write a test for the comment counter. 
- [Optional] Please make sure to test at least for the case where there is no comment, It should be set to 0. (Remember I'm not saying it's not working but we need to have a test case that asserts your website will work fine)
- [Optional] The comment counter should be implemented in a separate module, This is among the primary requirements I'm only making it optional because it has not been mentioned to you before.

2023-01-06 07:41 UTC, Tadesse-Alemayehu commented on src/module/displayMoviesData.js
> +    numberOfMovies.innerHTML = `${data.length} Tv Shows`;
- [ ] I like how you add the counter for movies here, but as the previous code reviewer mentioned the requirement is to still create a specific module to calculate numbers even if the API provides that information (just like the one you did for your like counter). one of the main requirements is: `Each counter should be implemented as a separate module.`

2023-01-06 08:21 UTC, michaelamponsah commented on src/module/displayMoviesData.js
> +    numberOfMovies.innerHTML = `${data.length} Tv Shows`;
@Tadesse-Alemayehu, 
Many thanks! You've given a clear and precise review.
I'll work to implement the changes requested.

2023-01-06 10:45 UTC, Tadesse-Alemayehu commented on src/module/displayMoviesData.js
> +    numberOfMovies.innerHTML = `${data.length} Tv Shows`;
Good job @michaelamponsah. 🙌

2023-01-06 14:19 UTC, muneebulrehman approved these changes
Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳
Congratulations! 🎉 

# Status: Approved✔️

## Highlights
- Descriptive PR
- No linter errors
- Good follow-up with the previous reviewers
- Good UI design.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-06 14:24 UTC, merged

2023-01-12 16:30 UTC, XRichardroidX commented on src/module/getSingleShowLike.js
> +};
Oh ok don't worry, changes has been made to that 👍 💯

2023-01-12 16:33 UTC, XRichardroidX commented on src/module/displayComments.js
> +};
That has been implemented now, thanks 🥇 .

2023-01-12 16:35 UTC, XRichardroidX commented on src/module/displayMoviesData.js
> +    numberOfMovies.innerHTML = `${data.length} Tv Shows`;
I see, that's true, That has been resolved now, Thanks for the corrections, I now understand what you were talking about 🥇 .